Update nvidia-x11-laptop-conf

diff --git a/Other/nvidia-x11-laptop-conf b/Other/nvidia-x11-laptop-conf
--- a/Other/nvidia-x11-laptop-conf
+++ b/Other/nvidia-x11-laptop-conf
@@ -1,9 +1,36 @@
-#!/bin/bash
-set -xe
-#    Workaround for NVidia GPUs using PRIME configuration.
-#    this will make output available on external ports.
+#!/usr/bin/env bash
+
+#############################################################################################################################################################################
+#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
+#                                                                                                                                                                           #
+#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
+#                                                                                                                                                                           #
+#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
+#                                                                                                                                                                           #
+#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
+#                                                                                                                                                                           #
+#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
+#       in the documentation and/or other materials provided with the distribution.                                                                                         #
+#                                                                                                                                                                           #
+#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
+#       without specific prior written permission.                                                                                                                          #
+#                                                                                                                                                                           #
+#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
+#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
+#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
+#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
+#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
+#############################################################################################################################################################################
+
+# -- Exit on errors.
+
+set -eu
+
+
+# -- Workaround for NVIDIA GPUs using PRIME configuration, this will make output available on external ports.
+
 test -f /usr/share/X11/xorg.conf.d/10-nvidia.conf && {
-    echo 'Nvidia Proprietary Driver installed!, adding X11 configuration.'
+    echo 'NVIDIA Proprietary Driver installed!, adding X11 configuration.'
         > /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf printf "%s\n" \
             'Section "OutputClass"' \
             '    Identifier "nvidia"' \
@@ -28,5 +55,5 @@ test -f /usr/share/X11/xorg.conf.d/10-nvidia.conf && {
         > /etc/modprobe.d/blacklist-nouveau.conf printf "%s\n" \
             'blacklist nouveau'
 } || {
-    echo 'Nvidia Proprietary Driver not installed!, skipping X11 configuration.'
+    echo 'NVIDIA Proprietary Driver not installed!, skipping X11 configuration.'
 }
